services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - "${FRONT_PORT:-3000}:80"

  backend:
    build: ./server
    container_name: server
    ports:
      - "${BACK_PORT:-8080}:8080"
